name: UI Pipeline

on:
  push:
    braches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Go to ui directory
        run: cd ui

      - name: Build container
        run: sudo docker build -t pomoticker .
