name: UI Pipeline

on:
  push:
    braches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Test
        run: echo "Testing pipeilne execution"
      - name: Reveal Path
        run: pwd
      - name: Test visibility
        run: ls
