name: UI Pipeline

on:
  push:
    braches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Navigate to build directory
        run: cd ~/home/ubuntu/pomoticker/ui
        
      - name: Pull latest changes
        run: git pull
